# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialtodo', '0002_auto_20160217_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collab1',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='collab2',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='collab3',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
